### ISSUE TITLE
Fix percentage off-scale calculation

### ISSUE THREAD

**Issue by NickRoach** [NickRoach/blackheath-wind-meter#50]
The percentage off-scale, i.e. ">6 m/s" when the units are "m/s" is wrong. It's too low. Needs fixing. This will be a frontEnd change, as the value is calculated client-side.

In this screenshot only one record is _not_ off scale, but the percentage off-scale is only 60%

![Screenshot_20240719-193839_Chrome.jpg](https://github.com/user-attachments/assets/dcbd52b4-064d-448a-94d0-d02982a34651)

**Comment by NickRoach** [comment]
and here all the observations were off the scale, but it says only 62%!

<img width="561" alt="image" src="https://github.com/user-attachments/assets/8492d924-e734-440c-a55b-c98b702caca5">

**Comment by burtscriptor** [comment]
From what I can understand aboveMax gets incremented when the speed is above the max for that unit of measurement.  -Line 219...
  } else aboveMax++
Then it is displayed to the user on line 231  but it is never used in a calculation to workout percentage.
This is the current line 231... 
- document.getElementById('outOfRange').textContent = `>${selectedUnit.max + ' ' + selectedUnit.label}: ${aboveMax}%`
And i believe what is needed is the addition of the calculation algorithm to that line...
- document.getElementById('outOfRange').textContent = `>${selectedUnit.max + ' ' + selectedUnit.label}: ${(aboveMax / (recordPack.data.length) * 100).toFixed(0)}%`

**Comment by NickRoach** [comment]
Ok. Sounds like you've found the relevant code! You should be able to test the code by just opening index.html with a browser, or you could use live server plugin for vs code. Once you've fixed the issue, can you please commit it to a new branch, then Google how to push your branch to this remote repo and make a pull request? Please reference the ticket in your pull request
